#!/usr/bin/env node
/**
 * Generate /env.js from environment variables at runtime
 * This allows injecting environment variables without rebuilding the Docker image
 * 
 * Usage: node scripts/generate-env.js [output-dir]
 * Output: [output-dir]/env.js (defaults to current directory)
 * 
 * In Docker: writes to /usr/share/nginx/html/env.js
 */

const fs = require('fs');
const path = require('path');

// Get output directory from command line argument or use current directory
const outputDir = process.argv[2] || process.cwd();

// Get environment variables (from Dokploy Environments or Docker env vars)
const envVars = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || '',
};

// Generate the env.js file content
const envJsContent = `// Runtime environment variables injected at container startup
// This file is generated by scripts/generate-env.js
// DO NOT edit manually - it will be overwritten on container restart

window.__ENV__ = ${JSON.stringify(envVars, null, 2)};
`;

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Write env.js file
const envJsPath = path.join(outputDir, 'env.js');
fs.writeFileSync(envJsPath, envJsContent, 'utf8');

console.log(`✅ Generated ${envJsPath}`);
console.log('Environment variables:');
Object.entries(envVars).forEach(([key, value]) => {
  const displayValue = value ? (value.length > 50 ? `${value.substring(0, 50)}...` : value) : '(empty)';
  console.log(`  ${key}: ${displayValue}`);
});

if (!envVars.NEXT_PUBLIC_API_URL) {
  console.warn('⚠️  WARNING: NEXT_PUBLIC_API_URL is not set!');
  console.warn('⚠️  Set it in Dokploy Environments or Docker environment variables');
}

